GRANT ALL PRIVILEGES ON DATABASE shop TO shop_user;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO shop_user;

GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO shop_user;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO shop_user;